static void selection_click_key(SceneEditor* editor,size_t channel,int64_t frame,bool add) {
    SDL_Rect row;assert(SceneEditorTimelineTrackRect(channel,&row));
    SDL_SetModState(add?KMOD_SHIFT:KMOD_NONE);
    click(editor,(SDL_Rect){SceneEditorTimelineFrameX(frame),row.y+row.h/2,1,1});
    SDL_SetModState(KMOD_NONE);
}
static void timeline_selection_acceptance(SceneEditor* editor,const char* path) {
    choose_menu(editor,-1,SCENE_WORKSPACE_RENDER);authoring_control(editor,"setup");authoring_control(editor,"frame_paths");
    static TimelineDocument doc;assert(SceneEditorDocumentGetTimeline(&doc)==TIMELINE_STATUS_OK);
    size_t camera=SIZE_MAX;for(size_t i=0;i<doc.track_count;++i) if(!strcmp(doc.tracks[i].property_id,"camera/path_progress")) camera=i;
    assert(camera!=SIZE_MAX);SDL_Rect row;assert(SceneEditorTimelineTrackRect(camera,&row));click(editor,row);
    authoring_control(editor,"frame");authoring_text(editor,"20");authoring_control(editor,"value");authoring_text(editor,"0.2");
    authoring_control(editor,"frame");authoring_text(editor,"40");authoring_control(editor,"value");authoring_text(editor,"0.4");
    authoring_control(editor,"frame");authoring_text(editor,"100");
    unsigned long long rev=SceneEditorDocumentRevision();selection_click_key(editor,camera,20,false);
    SceneEditorTimelineKeySelection keys;TimelineSample sample;
    assert(SceneEditorTimelineSelectionRead(&keys) && keys.count==1 && keys.primary.frame==20);
    assert(SceneEditorTimelineCurrentSample(&sample) && sample.absolute_frame==100 && SceneEditorDocumentRevision()==rev);
    authoring_control(editor,"key_value");authoring_text(editor,"not-a-number");
    assert(SceneEditorDocumentRevision()==rev);key(editor,SDLK_ESCAPE);
    authoring_control(editor,"key_value");authoring_text(editor,"0.25");
    assert(SceneEditorTimelineSelectionRead(&keys) && keys.primary.value.as.scalar==.25 && SceneEditorDocumentRevision()==rev+1);
    authoring_control(editor,"key_frame");authoring_text(editor,"24");
    assert(SceneEditorTimelineSelectionRead(&keys) && keys.primary.frame==24 && SceneEditorTimelineCurrentSample(&sample) && sample.absolute_frame==100);
    selection_click_key(editor,camera,40,true);
    assert(SceneEditorTimelineSelectionRead(&keys) && keys.count==2);
    assert(SceneEditorTimelineTrackRect(camera,&row));rev=SceneEditorDocumentRevision();
    dock_drag(editor,SceneEditorTimelineFrameX(24),row.y+row.h/2,SceneEditorTimelineFrameX(28),row.y+row.h/2,true);
    assert(SceneEditorDocumentRevision()==rev && SceneEditorTimelineSelectionRead(&keys) && keys.count==2);
    dock_drag(editor,SceneEditorTimelineFrameX(24),row.y+row.h/2,SceneEditorTimelineFrameX(28),row.y+row.h/2,false);
    assert(SceneEditorDocumentRevision()==rev+1 && SceneEditorTimelineKeySelected(doc.tracks[camera].track_id,28) && SceneEditorTimelineKeySelected(doc.tracks[camera].track_id,44));
    assert(SceneEditorTimelineCurrentSample(&sample) && sample.absolute_frame==100);
    authoring_control(editor,"copy_keys");authoring_control(editor,"frame");authoring_text(editor,"80");rev=SceneEditorDocumentRevision();
    authoring_control(editor,"paste_keys");
    assert(SceneEditorDocumentRevision()==rev+1 && SceneEditorTimelineSelectionRead(&keys) && keys.count==2);
    assert(SceneEditorTimelineKeySelected(doc.tracks[camera].track_id,80) && SceneEditorTimelineKeySelected(doc.tracks[camera].track_id,96));
    rev=SceneEditorDocumentRevision();authoring_control(editor,"duplicate_keys");assert(SceneEditorDocumentRevision()==rev);
    authoring_control(editor,"frame");authoring_text(editor,"120");authoring_control(editor,"duplicate_keys");
    assert(SceneEditorDocumentRevision()==rev+1 && SceneEditorTimelineKeySelected(doc.tracks[camera].track_id,120) && SceneEditorTimelineKeySelected(doc.tracks[camera].track_id,136));
    choose_menu(editor,1,0);assert(SceneEditorDocumentGetTimeline(&doc)==TIMELINE_STATUS_OK && doc.tracks[camera].key_count==6);
    assert(!SceneEditorTimelineSelectionRead(&keys));
    choose_menu(editor,1,1);assert(SceneEditorDocumentGetTimeline(&doc)==TIMELINE_STATUS_OK && doc.tracks[camera].key_count==8);
    selection_click_key(editor,camera,120,false);selection_click_key(editor,camera,136,true);rev=SceneEditorDocumentRevision();
    authoring_control(editor,"delete_keys");assert(SceneEditorDocumentRevision()==rev+1 && SceneEditorDocumentGetTimeline(&doc)==TIMELINE_STATUS_OK && doc.tracks[camera].key_count==6);
    choose_menu(editor,1,0);assert(SceneEditorDocumentGetTimeline(&doc)==TIMELINE_STATUS_OK && doc.tracks[camera].key_count==8);
    selection_click_key(editor,camera,120,false);authoring_control(editor,"next_key");
    assert(SceneEditorTimelineSelectionRead(&keys) && keys.primary.frame==136 && SceneEditorTimelineCurrentSample(&sample) && sample.absolute_frame==136);
    authoring_control(editor,"previous_key");assert(SceneEditorTimelineSelectionRead(&keys) && keys.primary.frame==120);
    authoring_control(editor,"frame");authoring_text(editor,"180");
    assert(SceneEditorTimelineSelectionRead(&keys) && keys.primary.frame==120 && SceneEditorTimelineCurrentSample(&sample) && sample.absolute_frame==180);
    capture(editor,"selection_independent.ppm");
    selection_click_key(editor,camera,136,true);capture(editor,"selection_multiple.ppm");
    dock_control(editor,"curves");capture(editor,"selection_curves.ppm");dock_control(editor,"keys");
    choose_menu(editor,0,0);char diagnostics[256];assert(SceneEditorDocumentOpen(path,diagnostics,sizeof(diagnostics)));
    assert(SceneEditorDocumentGetTimeline(&doc)==TIMELINE_STATUS_OK && doc.tracks[camera].key_count==8);
    SDL_SetWindowSize(editor->window,1000,700);SDL_PumpEvents();SceneEditorSessionRuntimeRender(editor);SceneEditorSessionRuntimeRender(editor);
    selection_click_key(editor,camera,28,false);authoring_control(editor,"frame");authoring_text(editor,"100");
    assert(SceneEditorTimelineSelectionRead(&keys) && keys.primary.frame==28);
    SDL_Rect control;assert(SceneEditorRenderAuthoringControl("delete_keys",&control));
    capture(editor,"selection_compact.ppm");
    fprintf(stderr,"Timeline selection UI PASS: independent scrub/selection, selected inspector time/value, Shift selection, atomic group drag/cancel, copy/paste/duplicate/collision, group delete/undo/redo, next/previous keys, save/reopen, compact inspector\n");
}
