/* Native acceptance against a task-owned copy of the real skull scene. */
static void skull_placement_acceptance(SceneEditor* editor,char** argv) {
        char diagnostic[256]={0};
        const int original_count=sceneSettings.objectCount;
        click(editor,addButton);
        assert(SceneEditorWorkspaceProfileMenuOpen());
        for(int step=0;step<2;++step) key(editor,SDLK_DOWN);
        key(editor,SDLK_RETURN);
        SceneEditorSessionRuntimeRender(editor);
        SDL_Event drop={0}; drop.type=SDL_DROPFILE; drop.drop.file=SDL_strdup(argv[4]);
        SceneEditorSessionRuntimeHandleEvent(editor,&drop);
        SceneEditorSessionRuntimeRender(editor);
        SDL_Rect apply;
        assert(SceneEditorTransformPanelImportApplyControl(&apply));
        click(editor,apply);
        Uint32 deadline=SDL_GetTicks()+30000;
        while(SceneEditorTransformPanelInteractionActive() && SDL_GetTicks()<deadline) {
            SceneEditorTransformPanelPoll(); SDL_PumpEvents();
            SceneEditorSessionRuntimeRender(editor); SDL_Delay(10);
        }
        assert(!SceneEditorTransformPanelInteractionActive());
        assert(sceneSettings.objectCount==original_count+1);
        const int imported=sceneSettings.objectCount-1;
        assert(ObjectEditorGetSelectedObjectIndex()==imported);
        SceneEditorDocumentTransform transform={0};
        assert(SceneEditorDocumentGetTransformForSceneIndex(imported,&transform,diagnostic,sizeof(diagnostic)));
        assert(transform.position[0]>-60 && transform.position[0]<60);
        assert(transform.position[1]>-60 && transform.position[1]<60);
        assert(fabs(transform.position[2])<1.0);
        assert(transform.scale[0]>0 && transform.scale[0]<1);
        SceneEditorPaneLayout placement_layout;
        RuntimeSceneBridge3DDigestState placement_digest={0};
        SceneEditorDigestOverlayProjector placement_projector={0};
        double pmin[3],pmax[3];
        assert(SceneEditorGetPaneLayout(&placement_layout));
        assert(SceneEditorDigestOverlayResolve(&placement_digest));
        assert(SceneEditorDigestOverlayBuildProjector(&placement_digest,&placement_layout.viewport_rect,
            SceneEditorGetViewportNavState(),&placement_projector));
        assert(SceneEditorDigestOverlayResolveObjectExtents(&placement_digest,imported,
            &pmin[0],&pmin[1],&pmin[2],&pmax[0],&pmax[1],&pmax[2],NULL));
        assert(SceneEditorMeshPreviewStoreHasSceneObject(imported));
        assert(!SceneEditorMeshPreviewStoreSceneObjectUsesBoundsFallback(imported));
        assert(pmax[0]-pmin[0]>10 && pmax[0]-pmin[0]<30);
        assert(pmax[1]-pmin[1]>10 && pmax[1]-pmin[1]<30);
        assert(pmax[2]-pmin[2]>10 && pmax[2]-pmin[2]<30);
        assert(SceneEditorGetViewportNavState()->overlay_zoom<1.0);
        capture(editor,"skull_import_placed.ppm");
        assert(SceneEditorFrameViewport(true));
        assert(SceneEditorGetViewportNavState()->overlay_zoom<1.0);
        SceneEditorSessionRuntimeRender(editor);
        capture(editor,"skull_frame_selected.ppm");
        transform.position[0]+=3.0;
        assert(SceneEditorDocumentSetTransformForSceneIndex(imported,&transform,diagnostic,sizeof(diagnostic)));
        SceneEditorSessionRuntimeRender(editor);
        capture(editor,"skull_moved.ppm");
        assert(SceneEditorDocumentUndo(diagnostic,sizeof(diagnostic)));
        SceneEditorDocumentTransform undone={0};
        assert(SceneEditorDocumentGetTransformForSceneIndex(imported,&undone,diagnostic,sizeof(diagnostic)));
        assert(fabs(undone.position[0]-(transform.position[0]-3.0))<1e-6);
        assert(SceneEditorDocumentRedo(diagnostic,sizeof(diagnostic)));
        assert(SceneEditorDocumentSave(diagnostic,sizeof(diagnostic)));
        assert(SceneEditorDocumentOpen(argv[2],diagnostic,sizeof(diagnostic)));
        assert(sceneSettings.objectCount==original_count+1);
        ObjectEditorSetSelectedObjectIndex(imported);
        SceneEditorSessionRuntimeRender(editor);
        SDL_Rect delete_button;
        bool pending=false;
        assert(SceneEditorTransformPanelDeleteControl(&delete_button,&pending) && !pending);
        unsigned long long revision=SceneEditorDocumentRevision();
        click(editor,delete_button);
        assert(sceneSettings.objectCount==original_count+1 && SceneEditorDocumentRevision()==revision);
        assert(SceneEditorTransformPanelDeleteControl(&delete_button,&pending) && pending);
        capture(editor,"skull_delete_confirmation.ppm");
        click(editor,delete_button);
        assert(sceneSettings.objectCount==original_count);
        assert(SceneEditorDocumentCanUndo());
        assert(SceneEditorDocumentUndo(diagnostic,sizeof(diagnostic)));
        assert(sceneSettings.objectCount==original_count+1);
        ObjectEditorSetSelectedObjectIndex(imported);
        SceneEditorSessionRuntimeRender(editor);
        assert(SceneEditorTransformPanelDeleteControl(&delete_button,&pending) && !pending);
        click(editor,delete_button); click(editor,delete_button);
        assert(sceneSettings.objectCount==original_count);
        assert(SceneEditorDocumentSave(diagnostic,sizeof(diagnostic)));
        assert(SceneEditorDocumentOpen(argv[2],diagnostic,sizeof(diagnostic)));
        assert(sceneSettings.objectCount==original_count);
        active_editor=NULL; DestroySceneEditor(editor); TTF_Quit(); SDL_Quit();
        puts("Skull placement, selection, frame, move, undo, delete confirmation, save and reopen passed");
        return;
}
