#ifndef TEST_RUNTIME_CAUSTIC_PHOTON_VOLUME_SEGMENT_NORMALIZATION_3D_H
#define TEST_RUNTIME_CAUSTIC_PHOTON_VOLUME_SEGMENT_NORMALIZATION_3D_H

int run_test_runtime_caustic_photon_volume_segment_normalization_3d_tests(void);

#endif
