#ifndef TEST_RUNTIME_CAUSTIC_PHOTON_SURFACE_PROVENANCE_FILTER_3D_H
#define TEST_RUNTIME_CAUSTIC_PHOTON_SURFACE_PROVENANCE_FILTER_3D_H

int run_test_runtime_caustic_photon_surface_provenance_filter_3d_tests(void);

#endif
