#!/usr/bin/env python3
"""Generate the compile-time worker identity from the canonical version file."""

from __future__ import annotations

import argparse
import os
import re
import tempfile
from pathlib import Path


SEMVER = re.compile(r"^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$")


def read_version(path: Path) -> str:
    version = path.read_text(encoding="utf-8").strip()
    if SEMVER.fullmatch(version) is None:
        raise ValueError(f"{path} must contain one canonical MAJOR.MINOR.PATCH version")
    return version


def header_text(version: str) -> str:
    return (
        "/* Generated from WORKER_VERSION. Do not edit this file directly. */\n"
        "#ifndef RAY_TRACING_WORKER_VERSION_GENERATED_H\n"
        "#define RAY_TRACING_WORKER_VERSION_GENERATED_H\n"
        f'#define RAY_TRACING_WORKER_RUNTIME_VERSION "{version}"\n'
        "#endif\n"
    )


def write_if_changed(path: Path, content: str) -> None:
    if path.is_file() and path.read_text(encoding="utf-8") == content:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{path.name}.", dir=path.parent
    )
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary_name, path)
    finally:
        if os.path.exists(temporary_name):
            os.unlink(temporary_name)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--version-file", type=Path, required=True)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    version = read_version(args.version_file)
    expected = header_text(version)
    if args.check:
        if args.output is not None:
            if not args.output.is_file() or args.output.read_text(encoding="utf-8") != expected:
                raise SystemExit("generated worker version header is stale")
        print(version)
        return 0
    if args.output is None:
        parser.error("--output is required unless --check is used")
    write_if_changed(args.output, expected)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
